#!/usr/bin/env zsh

# spread desktops
desktops=10
count=$(xrandr -q | grep -c ' connected')
i=1
for m in $(xrandr -q | grep ' connected' | awk '{print $1}'); do
  sequence=$(seq -s ' ' $(((1+(i-1)*desktops/count))) $((i*desktops/count)))
  bspc monitor "$m" -d $(echo ''${sequence//10/0})
  i=$((i+1))
done

# root window color
xsetroot -solid '#948CC7'
# pointer
xsetroot -cursor_name left_ptr
# turn off blanking
xset -dpms
xset s off
xset s noblank
numlockx on

# border color
bspc config focused_border_color  "#948CC7"
bspc config normal_border_color   "#2E2E2E"
bspc config border_width          "2"
bspc config window_gap            0
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        false
bspc config focus_follows_pointer false
bspc config automatic_scheme      spiral

sxhkd -m 1 &

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Rofi state=floating
bspc rule -a "-c" state=floating
bspc rule -a xcalc state=floating

